import Head from 'next/head'
import { Inter } from 'next/font/google'
import boldoLogo from '../../public/assets/Logo.png'
import { App } from '@/Components'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={boldoLogo} />
      </Head>
      <main >
        <App/>
      </main>
    </>
  )
}
